apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask
spec:
  type: NodePort # redirect to ports from pods to external
  selector:
    app: flask # works with pods with flask app label
  ports:
    - port: 80 # external
      targetPort: 80 # port in pod